### ISSUE TITLE
description for step function

### ISSUE THREAD

**Issue by aakhmetz** [nimble-dev/nimble-docs#11]
As in Table 5.4 of the documentation, what is the value of step-function at x=0?
In my opionion there should <= or >= at one side

**Comment by paciorek** [comment]
Thanks, we'll fix that in the next release -- step(0) is 0.

**Comment by aakhmetz** [comment]
Thanks!
Just not to mislead other people who would read this closed ticket - step(0) is actually 1 according to the new version of the documentation (~ p.118 for ver. 0.6-11)
