### ISSUE TITLE
Error in installation command

### ISSUE THREAD

**Issue by iagomosqueira** [nimble-dev/nimble-docs#16]
Not sure issues for the website should go here, but the installation command at https://r-nimble.org/download has a mix of single and double quotes

```
install.packages("nimble", repos = "http://r-nimble.org", type = "source')
```

should be

```
install.packages("nimble", repos = "http://r-nimble.org", type = "source")
```

**Comment by perrydv** [comment]
Thanks @iagomosqueira.  I fixed the web-page.
