### ISSUE TITLE
full dictionary of DSL functions?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimble-docs#2]
In chatting with someone trying to write a nimbleFunction, it occurred to me that perhaps we should have a complete list of all the things that are in the DSL so that function writers can look to see if a given function that exists in R is available in the DSL.  E.g., it came up that c(), rep(), and break() were not in the DSL.

**Comment by danielturek** [comment]
Good idea, Chris.  I saw Perry's email about the wiki, his beginnings.  I'll try to add to it this upcoming week.

Just my 2 cents, I'd say keep the wiki DSL descriptions short, mostly just a listing of DSL functions, and if folks want more info they can read the User Manual -- to keep it extremely low overhead to add things to the wiki.

**Comment by paciorek** [comment]
This was essentially done in the manual rewrite for 0.6-4.
